[package]
name = "const_env"
version = "0.1.0"
authors = ["Drake Tetreault <ekardnt@ekardnt.com>"]
edition = "2018"
description = "Configure const and static items by environment variables."
homepage = "https://github.com/EkardNT/const_env"
repository = "https://github.com/EkardNT/const_env"
readme = "README.md"
keywords = ["env", "envvar", "environment", "variable"]
categories = ["development-tools::build-utils", "config"]
license = "CC0-1.0"

[lib]
proc_macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.const_env_impl]
version = "0.1"
path = "../const_env_impl"